FROM node:18-alpine

WORKDIR /app

RUN apk update && \
    apk add --no-cache python3 make g++

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
